/**
 * resolve-name — unit tests for session name resolution.
 *
 * Covers the layered fallback in `resolveName`, the flavor-default detector,
 * the auto-numbering helper, and the auto-generated-name predicate used by
 * project-and-role adoption.
 *
 * No socket, no daemon — pure logic with an in-memory SQLite.
 */

import { describe, expect, it, beforeEach, afterEach } from "vitest"
import { Database } from "bun:sqlite"
import {
  adoptByProjectAndRole,
  adoptIdentity,
  assignFlavorName,
  detectFlavorDefault,
  isAutoGeneratedName,
  nextFlavorNumber,
  resolveName,
  type Flavor,
} from "../tools/lib/tribe/resolve-name.ts"

// ---------------------------------------------------------------------------
// Helpers — minimal in-memory sessions table matching the schema used by
// resolveName's queries. Real schema has more columns; resolveName only
// touches the ones below.
// ---------------------------------------------------------------------------

function makeDb(): Database {
  const db = new Database(":memory:")
  db.run(`CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL,
    project_id TEXT,
    claude_session_id TEXT,
    identity_token TEXT,
    updated_at INTEGER NOT NULL
  )`)
  return db
}

function insertSession(
  db: Database,
  fields: {
    id: string
    name: string
    role: string
    project_id?: string | null
    claude_session_id?: string | null
    identity_token?: string | null
    updated_at?: number
  },
): void {
  db.prepare(
    "INSERT INTO sessions (id, name, role, project_id, claude_session_id, identity_token, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
  ).run(
    fields.id,
    fields.name,
    fields.role,
    fields.project_id ?? null,
    fields.claude_session_id ?? null,
    fields.identity_token ?? null,
    fields.updated_at ?? Date.now(),
  )
}

const noActive = (): boolean => false

// ---------------------------------------------------------------------------
// detectFlavorDefault — recognizes shell-fallback patterns, not user names.
// ---------------------------------------------------------------------------

describe("detectFlavorDefault", () => {
  it("recognizes codex-<digits>-<digits> as codex flavor", () => {
    expect(detectFlavorDefault("codex-56775-56857")).toBe("codex")
    expect(detectFlavorDefault("codex-1-2")).toBe("codex")
  })

  it("recognizes gemini / kimi / pi / claude PPID-PID forms", () => {
    expect(detectFlavorDefault("gemini-100-200")).toBe("gemini")
    expect(detectFlavorDefault("kimi-1234-5678")).toBe("kimi")
    expect(detectFlavorDefault("pi-99-100")).toBe("pi")
    expect(detectFlavorDefault("claude-1-2")).toBe("claude")
  })

  it("recognizes bare flavor names (TRIBE_NAME=codex)", () => {
    expect(detectFlavorDefault("codex")).toBe("codex")
    expect(detectFlavorDefault("claude")).toBe("claude")
  })

  it("is case-insensitive on the flavor segment", () => {
    expect(detectFlavorDefault("CODEX-1-2")).toBe("codex")
    expect(detectFlavorDefault("Claude")).toBe("claude")
  })

  it("returns null for user-chosen names (verbatim passthrough)", () => {
    expect(detectFlavorDefault("foo")).toBeNull()
    expect(detectFlavorDefault("chief")).toBeNull()
    expect(detectFlavorDefault("@agent/3")).toBeNull()
    expect(detectFlavorDefault("codex-bjorn")).toBeNull()
    expect(detectFlavorDefault("kimi-review-pass")).toBeNull()
    expect(detectFlavorDefault("km")).toBeNull()
  })

  it("returns null for already-auto-numbered names", () => {
    // codex1 / claude2 are valid TARGETS of detectFlavorDefault but not
    // valid INPUTS — they're already auto-numbered, treating them as
    // flavor defaults would cause renumbering churn on every join.
    expect(detectFlavorDefault("codex1")).toBeNull()
    expect(detectFlavorDefault("claude2")).toBeNull()
  })

  it("returns null for empty / null / undefined", () => {
    expect(detectFlavorDefault("")).toBeNull()
    expect(detectFlavorDefault(null)).toBeNull()
    expect(detectFlavorDefault(undefined)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// nextFlavorNumber — lowest free integer scan.
// ---------------------------------------------------------------------------

describe("nextFlavorNumber", () => {
  it("returns 1 when no taken names", () => {
    expect(nextFlavorNumber("codex", new Set())).toBe(1)
  })

  it("returns 2 when codex1 is taken", () => {
    expect(nextFlavorNumber("codex", new Set(["codex1"]))).toBe(2)
  })

  it("skips gaps and picks the lowest free integer", () => {
    expect(nextFlavorNumber("codex", new Set(["codex1", "codex3"]))).toBe(2)
    expect(nextFlavorNumber("codex", new Set(["codex2", "codex3", "codex4"]))).toBe(1)
  })

  it("ignores names of other flavors", () => {
    // claude2 doesn't reserve codex2; flavors number independently.
    expect(nextFlavorNumber("codex", new Set(["claude1", "claude2", "kimi3"]))).toBe(1)
  })

  it("handles consecutive runs", () => {
    const taken = new Set(["codex1", "codex2", "codex3", "codex4", "codex5"])
    expect(nextFlavorNumber("codex", taken)).toBe(6)
  })
})

describe("assignFlavorName", () => {
  it("composes flavor + lowest free integer", () => {
    expect(assignFlavorName("codex", new Set())).toBe("codex1")
    expect(assignFlavorName("codex", new Set(["codex1"]))).toBe("codex2")
    expect(assignFlavorName("claude", new Set(["claude1", "claude3"]))).toBe("claude2")
  })
})

// ---------------------------------------------------------------------------
// isAutoGeneratedName — adoption gate.
// ---------------------------------------------------------------------------

describe("isAutoGeneratedName", () => {
  it("treats flavor-numbered names as auto-generated (don't adopt)", () => {
    expect(isAutoGeneratedName("codex1")).toBe(true)
    expect(isAutoGeneratedName("claude5")).toBe(true)
    expect(isAutoGeneratedName("kimi10")).toBe(true)
    expect(isAutoGeneratedName("gemini2")).toBe(true)
    expect(isAutoGeneratedName("pi1")).toBe(true)
  })

  it("treats user names as non-auto (adoptable)", () => {
    expect(isAutoGeneratedName("foo")).toBe(false)
    expect(isAutoGeneratedName("@agent/3")).toBe(false)
    expect(isAutoGeneratedName("bjorn-review")).toBe(false)
  })

  it("keeps existing rules: chief, member-, km-, agent-, user-", () => {
    expect(isAutoGeneratedName("chief")).toBe(true)
    expect(isAutoGeneratedName("member-12345")).toBe(true)
    expect(isAutoGeneratedName("km-42")).toBe(true)
    expect(isAutoGeneratedName("agent-abc123")).toBe(true)
    expect(isAutoGeneratedName("user-x1y2z3")).toBe(true)
  })

  it("flags dead rows", () => {
    expect(isAutoGeneratedName("foo-dead-1234")).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// resolveName — the layered fallback. The order is:
//
//   1. p.name set + flavor-default → assignFlavorName(...)
//   2. p.name set + explicit → verbatim
//   3. claudeSessionName → verbatim
//   4. adopted.name → verbatim
//   5. prior claude-session row → name
//   6. project-and-role adoption → name
//   7. role=chief → "chief"
//   8. fallback → claudeN
// ---------------------------------------------------------------------------

describe("resolveName", () => {
  let db: Database

  beforeEach(() => {
    db = makeDb()
  })

  afterEach(() => {
    db.close()
  })

  it("assigns codex1 when p.name is a codex shell-fallback default", () => {
    const name = resolveName({
      db,
      p: { name: "codex-56775-56857" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("codex1")
  })

  it("assigns codex2 when codex1 is taken (lowest-free-integer)", () => {
    const name = resolveName({
      db,
      p: { name: "codex-99999-88888" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(["codex1"]),
    })
    expect(name).toBe("codex2")
  })

  it("preserves explicit user names (TRIBE_NAME=foo wins)", () => {
    const name = resolveName({
      db,
      p: { name: "foo" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("foo")
  })

  it("preserves @agent/3 hat names", () => {
    const name = resolveName({
      db,
      p: { name: "@agent/3" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("@agent/3")
  })

  it("preserves chief when p.name=chief", () => {
    const name = resolveName({
      db,
      p: { name: "chief" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "chief",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("chief")
  })

  it("defaults to agent1 when no name signal and role=member", () => {
    // Was "claude1" before — changed to "agent1" because we can't reliably
    // tell which flavor (codex/claude/kimi) is connecting from the register
    // call. Sessions rename to a meaningful name from inside.
    const name = resolveName({
      db,
      p: {},
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("agent1")
  })

  it("defaults to chief when role=chief and no other signal", () => {
    const name = resolveName({
      db,
      p: {},
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "chief",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("chief")
  })

  it("uses claudeSessionName when p.name absent", () => {
    const name = resolveName({
      db,
      p: {},
      adopted: null,
      claudeSessionName: "my-named-session",
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("my-named-session")
  })

  it("ignores adopted.name — adoption removed 2026-05-14, sessions rename from inside", () => {
    // The adoption logic was removed because it caused a chief session to
    // register as "@agent/4" via stale claude_session_id matching.
    const name = resolveName({
      db,
      p: {},
      adopted: { id: "x", name: "ghost", role: "member" },
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("agent1")
  })

  it("ignores prior claude_session_id matches — adoption removed", () => {
    insertSession(db, {
      id: "p1",
      name: "research-spike",
      role: "member",
      claude_session_id: "sess-abc",
    })
    const name = resolveName({
      db,
      p: {},
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: "sess-abc",
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: new Set(),
    })
    expect(name).toBe("agent1")
  })
})

// ---------------------------------------------------------------------------
// adoptByProjectAndRole / adoptIdentity smoke tests — these are the helpers
// used by the dispatcher; assert they still work after the refactor.
// ---------------------------------------------------------------------------

describe("adoptByProjectAndRole", () => {
  it("returns a non-active, non-auto prior session at same project+role", () => {
    const db = makeDb()
    insertSession(db, { id: "p1", name: "review-bot", role: "member", project_id: "P" })
    const got = adoptByProjectAndRole(db, "P", "member", noActive)
    expect(got?.name).toBe("review-bot")
  })

  it("skips auto-generated names", () => {
    const db = makeDb()
    insertSession(db, { id: "p1", name: "codex1", role: "member", project_id: "P" })
    insertSession(db, { id: "p2", name: "chief", role: "member", project_id: "P" })
    const got = adoptByProjectAndRole(db, "P", "member", noActive)
    expect(got).toBeNull()
  })

  it("skips active sessions", () => {
    const db = makeDb()
    insertSession(db, { id: "p1", name: "review-bot", role: "member", project_id: "P" })
    const got = adoptByProjectAndRole(db, "P", "member", (sid) => sid === "p1")
    expect(got).toBeNull()
  })
})

describe("adoptIdentity", () => {
  it("returns prior row matching identity_token when not active", () => {
    const db = makeDb()
    insertSession(db, { id: "p1", name: "ghost", role: "member", identity_token: "abc" })
    const got = adoptIdentity(db, "abc", noActive)
    expect(got?.name).toBe("ghost")
  })

  it("returns null when active", () => {
    const db = makeDb()
    insertSession(db, { id: "p1", name: "ghost", role: "member", identity_token: "abc" })
    expect(adoptIdentity(db, "abc", () => true)).toBeNull()
  })

  it("returns null without an identity token", () => {
    const db = makeDb()
    expect(adoptIdentity(db, null, noActive)).toBeNull()
  })
})

// ---------------------------------------------------------------------------
// Integration scenario — simulates the bead's acceptance criteria 1+2:
//
//   Three codex MCP clients connect in sequence; each registers with a
//   distinct PPID-PID name. Expect codex1, codex2, codex3 respectively.
// ---------------------------------------------------------------------------

describe("scenario: three sequential codex spawns", () => {
  it("assigns codex1, codex2, codex3 in order", () => {
    const db = makeDb()
    const taken = new Set<string>()

    const first = resolveName({
      db,
      p: { name: "codex-1000-2000" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: taken,
    })
    expect(first).toBe("codex1")
    taken.add(first)

    const second = resolveName({
      db,
      p: { name: "codex-3000-4000" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: taken,
    })
    expect(second).toBe("codex2")
    taken.add(second)

    const third = resolveName({
      db,
      p: { name: "codex-5000-6000" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: taken,
    })
    expect(third).toBe("codex3")
  })

  it("after codex1 disconnects, the next codex spawn reclaims codex1", () => {
    const db = makeDb()
    // codex2 + codex3 are still live; codex1 has disconnected (not in taken).
    const taken = new Set(["codex2", "codex3"])
    const name = resolveName({
      db,
      p: { name: "codex-7000-8000" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: taken,
    })
    expect(name).toBe("codex1")
  })

  it("mixed flavors number independently (codex + claude + kimi)", () => {
    const db = makeDb()
    const taken = new Set<string>()

    // codex1
    taken.add(
      resolveName({
        db,
        p: { name: "codex-1-2" },
        adopted: null,
        claudeSessionName: null,
        claudeSessionId: null,
        role: "member",
        isActive: noActive,
        projectId: "proj",
        takenNames: taken,
      }),
    )
    // kimi1
    taken.add(
      resolveName({
        db,
        p: { name: "kimi-3-4" },
        adopted: null,
        claudeSessionName: null,
        claudeSessionId: null,
        role: "member",
        isActive: noActive,
        projectId: "proj",
        takenNames: taken,
      }),
    )
    // claude1 (no name, fallback)
    taken.add(
      resolveName({
        db,
        p: {},
        adopted: null,
        claudeSessionName: null,
        claudeSessionId: null,
        role: "member",
        isActive: noActive,
        projectId: "proj",
        takenNames: taken,
      }),
    )

    // Fallback (no p.name) now produces "agent1" instead of "claude1" — the
    // daemon can't reliably tell which flavor it's talking to from the
    // register call. Sessions rename to a meaningful name from inside.
    expect(taken).toEqual(new Set(["codex1", "kimi1", "agent1"]))
  })

  it("TRIBE_NAME=foo overrides everything; flavor-numbering doesn't run", () => {
    const db = makeDb()
    const taken = new Set(["foo"]) // simulating: foo is already live
    // Note: this scenario tests resolveName output — deduplicateName in the
    // dispatcher rejects "foo" if already taken. Here we just verify that
    // user-named "foo" passes through verbatim (no flavor logic kicks in).
    const name = resolveName({
      db,
      p: { name: "foo" },
      adopted: null,
      claudeSessionName: null,
      claudeSessionId: null,
      role: "member",
      isActive: noActive,
      projectId: "proj",
      takenNames: taken,
    })
    expect(name).toBe("foo")
  })
})

// ---------------------------------------------------------------------------
// Type-level smoke — Flavor union covers exactly the documented set.
// ---------------------------------------------------------------------------

describe("Flavor union", () => {
  it("contains codex, claude, kimi, gemini, pi", () => {
    const _all: Flavor[] = ["codex", "claude", "kimi", "gemini", "pi"]
    expect(_all.length).toBe(5)
  })
})
